//************************************************************************************
//**  
//**  File name:     D:\Zer01 Electronics\Q_Proj_R14\FC2\Q_Proj_14_V2.c
//**  Title:         
//**  Description:   
//**  
//**  Generated by:  Flowcode v5.2.0.0
//**  Date:          Wednesday, September 21, 2022 13:40:37
//**  Licence:       Professional
//**  Registered to: xyz
//**  Licence key:   WUK7B9
//**  
//**  
//**  http://www.matrixmultimedia.com
//**  
//************************************************************************************


#define MX_PIC

#define MX_USES_UINT8 1
#define MX_USES_SINT16 0
#define MX_USES_CHAR 0
#define MX_USES_FLOAT 0
#define MX_USES_SINT32 0
#define MX_USES_BOOL 1
#define MX_USES_UINT16 1
#define MX_USES_UINT32 0
//Defines for microcontroller
#define P16F628A
#define FC_CAL_PIC
#define MX_EE
#define MX_EE_SIZE 128
#define MX_UART_1
#define MX_UART_1_TX_PORT portb
#define MX_UART_1_TX_TRIS trisb
#define MX_UART_1_TX_PIN 2
#define MX_UART_1_RX_PORT portb
#define MX_UART_1_RX_TRIS trisb
#define MX_UART_1_RX_PIN 1
#define MX_PWM
#define MX_PWM_CNT 1
#define MX_PWM_PSCA1
#define MX_PWM_PSCA4
#define MX_PWM_PSCA16
#define MX_PWM_1_PORT portb
#define MX_PWM_1_TRIS trisb
#define MX_PWM_1_PIN 3

//Functions
#define MX_CLK_SPEED 20000000
#ifdef _BOOSTC
#include <system.h>
#endif
#ifdef HI_TECH_C
#include <pic.h>
#endif

//Configuration data
#ifdef _BOOSTC
#pragma DATA 0x2007, 0x3f0a
#endif
#ifdef HI_TECH_C
__CONFIG(0x3f0a);
#endif

//Internal functions
#include "C:\Program Files (x86)\Flowcode\v5\FCD\internals.c"

//Macro function declarations
void FCM_SevenSegment();
void FCM_clk_pulse();
void FCM_Scan_ShiftReg();
void FCM_Display_7Seg();
void FCM_DISPLAY_BOARD_DATA();
void FCM_Interrupt();
void FCM_btn_scan1();
void FCM_btn_scan2();
void FCM_btn_scan3();
void FCM_button_conditions();
void FCM_TIMEKEEP();
void FCM_DISPLAY_BLINKING();
void FCM_button_condition_SETTING();


//Variable declarations
#define FCV_TRUE (1)
#define FCV_FALSE (0)
MX_BOOL FCV_BTN_HOME = (1);
MX_BOOL FCV_BTN_SHIFT = (1);
MX_UINT8 FCV_BLINK_COUNT = (0x0);
MX_UINT8 FCV_SCAN1 = (0xff);
MX_BOOL FCV_TOGGLE_SHOTCLOCK = (0);
MX_BOOL FCV_DAT = (0);
MX_UINT8 FCV_SCAN2 = (0xff);
MX_UINT8 FCV_BTN_SHOTCLOCK = (0x1);
MX_UINT8 FCV_PERIOD = (0x1);
MX_BOOL FCV_TOGGLE_GUEST = (0);
MX_UINT8 FCV_GAMETIME_SEC;
MX_UINT8 FCV_GAMETIME_MIN = (0xa);
MX_UINT8 FCV_DISPLAY_SEVENSEG = (0xff);
MX_BOOL FCV_TOGGLE_STARTSTOP = (0);
MX_BOOL FCV_BTN_STARTSTOP = (1);
MX_BOOL FCV_SWITCH4 = (1);
MX_BOOL FCV_SHIFTING = (0);
MX_BOOL FCV_TOGGLE_HOME = (0);
MX_BOOL FCV_SWITCH5 = (1);
MX_UINT8 FCV_GUESTSCORE = (0x0);
MX_BOOL FCV_BTN_GUEST = (1);
MX_UINT8 FCV_HOMESCORE = (0x0);
MX_UINT8 FCV_BUTTON_SCAN = (0x0);
MX_UINT8 FCV_SHOTCLOCK = (0x18);
MX_UINT16 FCV_TIME_COUNTER = (0x0);
MX_BOOL FCV_FLAG_STARTSTOP = (0);
MX_BOOL FCV_FLAG_SETTIME = (0);
MX_UINT8 FCV_TEMP_SCAN1 = (0x0);
MX_UINT8 FCV_TODISPLAY_SS = (0xff);
MX_UINT8 FCV_TO_SET = (0x0);
MX_BOOL FCV_BTN_BUZZER = (1);
MX_UINT8 FCV_TEMP_SCAN2 = (0x0);

MX_UINT8 FCLV_LOOP1;
MX_UINT8 FCLV_LOOP2;
MX_UINT8 FCLV_LOOP3;


#include "C:\Program Files (x86)\Flowcode\v5\CAL\includes.c"

//Macro implementations


void FCM_SevenSegment()
{

	//Switch
	//Switch: display_sevenseg?
	switch (FCV_DISPLAY_SEVENSEG)
	{
		case 1:
		{
			//Output
			//Output: 0b00000110 -> PORTB
			trisb = 0x00;
			portb = (6);

			break;
		}
		case 2:
		{
			//Output
			//Output: 0b01011011 -> PORTB
			trisb = 0x00;
			portb = (91);

			break;
		}
		case 3:
		{
			//Output
			//Output: 0b01001111 -> PORTB
			trisb = 0x00;
			portb = (79);

			break;
		}
		case 4:
		{
			//Output
			//Output: 0b01100110 -> PORTB
			trisb = 0x00;
			portb = (102);

			break;
		}
		case 5:
		{
			//Output
			//Output: 0b01101101 -> PORTB
			trisb = 0x00;
			portb = (109);

			break;
		}
		case 6:
		{
			//Output
			//Output: 0b01111101 -> PORTB
			trisb = 0x00;
			portb = (125);

			break;
		}
		case 7:
		{
			//Output
			//Output: 0b00000111 -> PORTB
			trisb = 0x00;
			portb = (7);

			break;
		}
		case 8:
		{
			//Output
			//Output: 0b01111111 -> PORTB
			trisb = 0x00;
			portb = (127);

			break;
		}
		case 9:
		{
			//Output
			//Output: 0b01101111 -> PORTB
			trisb = 0x00;
			portb = (111);

			break;
		}
		case 0:
		{
			//Output
			//Output: 0b00111111 -> PORTB
			trisb = 0x00;
			portb = (63);

			break;
		}
		default:
		{
			//Switch
			//Switch: display_sevenseg?
			switch (FCV_DISPLAY_SEVENSEG)
			{
				case 10:
				{
					//Output
					//Output: 0b01110011 -> PORTB
					trisb = 0x00;
					portb = (115);

					break;
				}
				case 255:
				{
					//Output
					//Output: 0b00000000 -> PORTB
					trisb = 0x00;
					portb = (0);

					break;
				}
				// default:

			}

		}
	}

}


void FCM_clk_pulse()
{

	//clk
	//Output: 1 -> A4
	trisa = trisa & 0xEF;
	if ((1))
		porta = (porta & 0xEF) | 0x10;
	else
		porta = porta & 0xEF;

	//clk
	//Output: 0 -> A4
	trisa = trisa & 0xEF;
	if ((0))
		porta = (porta & 0xEF) | 0x10;
	else
		porta = porta & 0xEF;

}


void FCM_Scan_ShiftReg()
{

	//Loop
	//Loop: Loop 8 times
	for (FCLV_LOOP2=0; FCLV_LOOP2<8; FCLV_LOOP2++)
	{

		//Calculation
		//Calculation:
		//  dat = scan1 AND 1
		FCV_DAT = FCV_SCAN1 & 1;

		//Output
		//Output: dat -> A3
		trisa = trisa & 0xF7;
		if ((FCV_DAT))
			porta = (porta & 0xF7) | 0x08;
		else
			porta = porta & 0xF7;

		//Call Macro
		//Call Macro: clk_pulse()
		FCM_clk_pulse();

		//Calculation
		//Calculation:
		//  scan1 = scan1 >> 1
		FCV_SCAN1 = FCV_SCAN1 >> 1;


	}

	//Loop
	//Loop: Loop 8 times
	for (FCLV_LOOP3=0; FCLV_LOOP3<8; FCLV_LOOP3++)
	{

		//Calculation
		//Calculation:
		//  dat = scan2 AND 1
		FCV_DAT = FCV_SCAN2 & 1;

		//Output
		//Output: dat -> A3
		trisa = trisa & 0xF7;
		if ((FCV_DAT))
			porta = (porta & 0xF7) | 0x08;
		else
			porta = porta & 0xF7;

		//Call Macro
		//Call Macro: clk_pulse()
		FCM_clk_pulse();

		//Calculation
		//Calculation:
		//  scan2 = scan2 >> 1
		FCV_SCAN2 = FCV_SCAN2 >> 1;


	}

}


void FCM_Display_7Seg()
{

	//Comment:
	//IWAS FLICKER

	//Calculation
	//Calculation:
	//  display_sevenseg = 255
	FCV_DISPLAY_SEVENSEG = 255;

	//Call Macro
	//Call Macro: SevenSegment()
	FCM_SevenSegment();

	//Call Macro
	//Call Macro: Scan_ShiftReg()
	FCM_Scan_ShiftReg();

	//Calculation
	//Calculation:
	//  display_sevenseg = TODISPLAY_SS
	FCV_DISPLAY_SEVENSEG = FCV_TODISPLAY_SS;

	//Call Macro
	//Call Macro: SevenSegment()
	FCM_SevenSegment();

	//Delay
	//Delay: 250 us
	delay_us(250);

}


void FCM_DISPLAY_BOARD_DATA()
{

	//Comment:
	//SHOTCLOCK

	//Calculation
	//Calculation:
	//  scan1 = 0x10
	//  scan2 = 0x00
	//  TODISPLAY_SS = SHOTCLOCK / 10
	FCV_SCAN1 = 0x10;
	FCV_SCAN2 = 0x00;
	FCV_TODISPLAY_SS = FCV_SHOTCLOCK / 10;

	//Decision
	//Decision: TODISPLAY_SS = 0?
	if (FCV_TODISPLAY_SS == 0)
	{

		//Calculation
		//Calculation:
		//  TODISPLAY_SS = 255
		FCV_TODISPLAY_SS = 255;

	// } else {

	}

	//Call Macro
	//Call Macro: Display_7Seg()
	FCM_Display_7Seg();

	//Calculation
	//Calculation:
	//  scan1 = 0x08
	//  scan2 = 0x00
	//  TODISPLAY_SS = SHOTCLOCK MOD 10
	FCV_SCAN1 = 0x08;
	FCV_SCAN2 = 0x00;
	FCV_TODISPLAY_SS = FCV_SHOTCLOCK % 10;

	//Call Macro
	//Call Macro: Display_7Seg()
	FCM_Display_7Seg();

	//Comment:
	//GAMETIME

	//Calculation
	//Calculation:
	//  scan1 = 0x00
	//  scan2 = 0x80
	//  TODISPLAY_SS = GAMETIME_MIN / 10
	FCV_SCAN1 = 0x00;
	FCV_SCAN2 = 0x80;
	FCV_TODISPLAY_SS = FCV_GAMETIME_MIN / 10;

	//Decision
	//Decision: TODISPLAY_SS = 0?
	if (FCV_TODISPLAY_SS == 0)
	{

		//Calculation
		//Calculation:
		//  TODISPLAY_SS = 255
		FCV_TODISPLAY_SS = 255;

	// } else {

	}

	//Call Macro
	//Call Macro: Display_7Seg()
	FCM_Display_7Seg();

	//Calculation
	//Calculation:
	//  scan1 = 0x00
	//  scan2 = 0x40
	//  TODISPLAY_SS = GAMETIME_MIN MOD 10
	FCV_SCAN1 = 0x00;
	FCV_SCAN2 = 0x40;
	FCV_TODISPLAY_SS = FCV_GAMETIME_MIN % 10;

	//Call Macro
	//Call Macro: Display_7Seg()
	FCM_Display_7Seg();

	//Calculation
	//Calculation:
	//  scan1 = 0x00
	//  scan2 = 0x20
	//  TODISPLAY_SS = GAMETIME_SEC / 10
	FCV_SCAN1 = 0x00;
	FCV_SCAN2 = 0x20;
	FCV_TODISPLAY_SS = FCV_GAMETIME_SEC / 10;

	//Call Macro
	//Call Macro: Display_7Seg()
	FCM_Display_7Seg();

	//Calculation
	//Calculation:
	//  scan1 = 0x00
	//  scan2 = 0x10
	//  TODISPLAY_SS = GAMETIME_SEC MOD 10
	FCV_SCAN1 = 0x00;
	FCV_SCAN2 = 0x10;
	FCV_TODISPLAY_SS = FCV_GAMETIME_SEC % 10;

	//Call Macro
	//Call Macro: Display_7Seg()
	FCM_Display_7Seg();

	//Comment:
	//HOME SCORE

	//Calculation
	//Calculation:
	//  scan1 = 0x00
	//  scan2 = 0x08
	//  TODISPLAY_SS = HOMESCORE / 100
	FCV_SCAN1 = 0x00;
	FCV_SCAN2 = 0x08;
	FCV_TODISPLAY_SS = FCV_HOMESCORE / 100;

	//Decision
	//Decision: TODISPLAY_SS = 0?
	if (FCV_TODISPLAY_SS == 0)
	{

		//Calculation
		//Calculation:
		//  TODISPLAY_SS = 255
		FCV_TODISPLAY_SS = 255;

	// } else {

	}

	//Call Macro
	//Call Macro: Display_7Seg()
	FCM_Display_7Seg();

	//Calculation
	//Calculation:
	//  scan1 = 0x00
	//  scan2 = 0x04
	//  TODISPLAY_SS = (HOMESCORE MOD 100) / 10
	FCV_SCAN1 = 0x00;
	FCV_SCAN2 = 0x04;
	FCV_TODISPLAY_SS = (FCV_HOMESCORE % 100) / 10;

	//Decision
	//Decision: TODISPLAY_SS = 0 AND HOMESCORE < 100?
	if (FCV_TODISPLAY_SS == 0 & FCV_HOMESCORE < 100)
	{

		//Calculation
		//Calculation:
		//  TODISPLAY_SS = 255
		FCV_TODISPLAY_SS = 255;

	// } else {

	}

	//Call Macro
	//Call Macro: Display_7Seg()
	FCM_Display_7Seg();

	//Calculation
	//Calculation:
	//  scan1 = 0x00
	//  scan2 = 0x02
	//  TODISPLAY_SS = HOMESCORE MOD 10
	FCV_SCAN1 = 0x00;
	FCV_SCAN2 = 0x02;
	FCV_TODISPLAY_SS = FCV_HOMESCORE % 10;

	//Call Macro
	//Call Macro: Display_7Seg()
	FCM_Display_7Seg();

	//Comment:
	//GUEST SCORE

	//Calculation
	//Calculation:
	//  scan1 = 0x00
	//  scan2 = 0x01
	//  TODISPLAY_SS = GUESTSCORE / 100
	FCV_SCAN1 = 0x00;
	FCV_SCAN2 = 0x01;
	FCV_TODISPLAY_SS = FCV_GUESTSCORE / 100;

	//Decision
	//Decision: TODISPLAY_SS = 0?
	if (FCV_TODISPLAY_SS == 0)
	{

		//Calculation
		//Calculation:
		//  TODISPLAY_SS = 255
		FCV_TODISPLAY_SS = 255;

	// } else {

	}

	//Call Macro
	//Call Macro: Display_7Seg()
	FCM_Display_7Seg();

	//Calculation
	//Calculation:
	//  scan1 = 0x80
	//  scan2 = 0x00
	//  TODISPLAY_SS = (GUESTSCORE MOD 100) / 10
	FCV_SCAN1 = 0x80;
	FCV_SCAN2 = 0x00;
	FCV_TODISPLAY_SS = (FCV_GUESTSCORE % 100) / 10;

	//Decision
	//Decision: TODISPLAY_SS = 0 AND GUESTSCORE < 100?
	if (FCV_TODISPLAY_SS == 0 & FCV_GUESTSCORE < 100)
	{

		//Calculation
		//Calculation:
		//  TODISPLAY_SS = 255
		FCV_TODISPLAY_SS = 255;

	// } else {

	}

	//Call Macro
	//Call Macro: Display_7Seg()
	FCM_Display_7Seg();

	//Calculation
	//Calculation:
	//  scan1 = 0x40
	//  scan2 = 0x00
	//  TODISPLAY_SS = GUESTSCORE MOD 10
	FCV_SCAN1 = 0x40;
	FCV_SCAN2 = 0x00;
	FCV_TODISPLAY_SS = FCV_GUESTSCORE % 10;

	//Call Macro
	//Call Macro: Display_7Seg()
	FCM_Display_7Seg();

	//Comment:
	//PERIOD

	//Calculation
	//Calculation:
	//  scan1 = 0x04
	//  scan2 = 0x00
	//  TODISPLAY_SS = PERIOD
	FCV_SCAN1 = 0x04;
	FCV_SCAN2 = 0x00;
	FCV_TODISPLAY_SS = FCV_PERIOD;

	//Call Macro
	//Call Macro: Display_7Seg()
	FCM_Display_7Seg();

}


void FCM_Interrupt()
{

	//Calculation
	//Calculation:
	//  temp_scan1 = scan1
	//  temp_scan2 = scan2
	FCV_TEMP_SCAN1 = FCV_SCAN1;
	FCV_TEMP_SCAN2 = FCV_SCAN2;

	//Switch
	//Switch: button_SCAN?
	switch (FCV_BUTTON_SCAN)
	{
		case 1:
		{
			//Call Macro
			//Call Macro: btn_scan1()
			FCM_btn_scan1();

			break;
		}
		case 2:
		{
			//Call Macro
			//Call Macro: btn_scan2()
			FCM_btn_scan2();

			break;
		}
		case 3:
		{
			//Call Macro
			//Call Macro: btn_scan3()
			FCM_btn_scan3();

			break;
		}
		// default:

	}

	//Calculation
	//Calculation:
	//  button_SCAN = button_SCAN + 1
	FCV_BUTTON_SCAN = FCV_BUTTON_SCAN + 1;

	//Decision
	//Decision: button_SCAN >= 4?
	if (FCV_BUTTON_SCAN >= 4)
	{

		//Calculation
		//Calculation:
		//  button_SCAN = 1
		FCV_BUTTON_SCAN = 1;

	// } else {

	}

	//Calculation
	//Calculation:
	//  scan1 = temp_scan1
	//  scan2 = temp_scan2
	FCV_SCAN1 = FCV_TEMP_SCAN1;
	FCV_SCAN2 = FCV_TEMP_SCAN2;

}


void FCM_btn_scan1()
{

	//Output
	//Output: 0b00000000 -> PORTB
	trisb = 0x00;
	portb = (0);

	//Calculation
	//Calculation:
	//  scan1 = 0x04
	//  scan2 = 0x00
	FCV_SCAN1 = 0x04;
	FCV_SCAN2 = 0x00;

	//Call Macro
	//Call Macro: Scan_ShiftReg()
	FCM_Scan_ShiftReg();

	//Input
	//Input: A0 -> switch4
	trisa = trisa | 0x01;
	FCV_SWITCH4 = ((porta & 0x01) == 0x01);

	//Input
	//Input: A1 -> switch5
	trisa = trisa | 0x02;
	FCV_SWITCH5 = ((porta & 0x02) == 0x02);

	//Decision
	//Decision: switch4 = 0?
	if (FCV_SWITCH4 == 0)
	{

		//Calculation
		//Calculation:
		//  btn_guest = 1
		FCV_BTN_GUEST = 1;

	} else {

		//Calculation
		//Calculation:
		//  btn_guest = 0
		//  toggle_guest = 0
		FCV_BTN_GUEST = 0;
		FCV_TOGGLE_GUEST = 0;

		//Decision
		//Decision: switch5 = 0?
		if (FCV_SWITCH5 == 0)
		{

			//Calculation
			//Calculation:
			//  btn_buzzer = 1
			FCV_BTN_BUZZER = 1;

		} else {

			//Calculation
			//Calculation:
			//  btn_buzzer = 0
			FCV_BTN_BUZZER = 0;

		}

	}

}


void FCM_btn_scan2()
{

	//Output
	//Output: 0b00000000 -> PORTB
	trisb = 0x00;
	portb = (0);

	//Calculation
	//Calculation:
	//  scan1 = 0x08
	//  scan2 = 0x00
	FCV_SCAN1 = 0x08;
	FCV_SCAN2 = 0x00;

	//Call Macro
	//Call Macro: Scan_ShiftReg()
	FCM_Scan_ShiftReg();

	//Input
	//Input: A0 -> switch4
	trisa = trisa | 0x01;
	FCV_SWITCH4 = ((porta & 0x01) == 0x01);

	//Input
	//Input: A1 -> switch5
	trisa = trisa | 0x02;
	FCV_SWITCH5 = ((porta & 0x02) == 0x02);

	//Decision
	//Decision: switch4 = 0?
	if (FCV_SWITCH4 == 0)
	{

		//Calculation
		//Calculation:
		//  btn_startstop = 1
		FCV_BTN_STARTSTOP = 1;

	} else {

		//Calculation
		//Calculation:
		//  btn_startstop = 0
		//  toggle_startstop = 0
		FCV_BTN_STARTSTOP = 0;
		FCV_TOGGLE_STARTSTOP = 0;

		//Decision
		//Decision: switch5 = 0?
		if (FCV_SWITCH5 == 0)
		{

			//Calculation
			//Calculation:
			//  btn_shift = 1
			FCV_BTN_SHIFT = 1;

		} else {

			//Calculation
			//Calculation:
			//  btn_shift = 0
			FCV_BTN_SHIFT = 0;

		}

	}

}


void FCM_btn_scan3()
{

	//Output
	//Output: 0b00000000 -> PORTB
	trisb = 0x00;
	portb = (0);

	//Calculation
	//Calculation:
	//  scan1 = 0x10
	//  scan2 = 0x00
	FCV_SCAN1 = 0x10;
	FCV_SCAN2 = 0x00;

	//Call Macro
	//Call Macro: Scan_ShiftReg()
	FCM_Scan_ShiftReg();

	//Input
	//Input: A0 -> switch4
	trisa = trisa | 0x01;
	FCV_SWITCH4 = ((porta & 0x01) == 0x01);

	//Input
	//Input: A1 -> switch5
	trisa = trisa | 0x02;
	FCV_SWITCH5 = ((porta & 0x02) == 0x02);

	//Decision
	//Decision: switch4 = 0?
	if (FCV_SWITCH4 == 0)
	{

		//Calculation
		//Calculation:
		//  btn_home = 1
		FCV_BTN_HOME = 1;

	} else {

		//Calculation
		//Calculation:
		//  btn_home = 0
		//  toggle_home = 0
		FCV_BTN_HOME = 0;
		FCV_TOGGLE_HOME = 0;

		//Decision
		//Decision: switch5 = 0?
		if (FCV_SWITCH5 == 0)
		{

			//Calculation
			//Calculation:
			//  btn_shotclock = 1
			FCV_BTN_SHOTCLOCK = 1;

		} else {

			//Calculation
			//Calculation:
			//  btn_shotclock = 0
			//  toggle_shotclock = 0
			FCV_BTN_SHOTCLOCK = 0;
			FCV_TOGGLE_SHOTCLOCK = 0;

		}

	}

}


void FCM_button_conditions()
{

	//Decision
	//Decision: btn_buzzer = 1?
	if (FCV_BTN_BUZZER == 1)
	{

		//BUZZER
		//Output: 1 -> B7
		trisb = trisb & 0x7F;
		if ((1))
			portb = (portb & 0x7F) | 0x80;
		else
			portb = portb & 0x7F;

	} else {

		//BUZZER
		//Output: 0 -> B7
		trisb = trisb & 0x7F;
		if ((0))
			portb = (portb & 0x7F) | 0x80;
		else
			portb = portb & 0x7F;

	}

	//Decision
	//Decision: btn_home = 1 AND toggle_home = 0?
	if (FCV_BTN_HOME == 1 & FCV_TOGGLE_HOME == 0)
	{

		//Decision
		//Decision: btn_shift = 1?
		if (FCV_BTN_SHIFT == 1)
		{

			//Calculation
			//Calculation:
			//  HOMESCORE = HOMESCORE - 1
			FCV_HOMESCORE = FCV_HOMESCORE - 1;

		} else {

			//Calculation
			//Calculation:
			//  HOMESCORE = HOMESCORE + 1
			FCV_HOMESCORE = FCV_HOMESCORE + 1;

		}

		//Decision
		//Decision: HOMESCORE >= 200 AND HOMESCORE < 255?
		if (FCV_HOMESCORE >= 200 & FCV_HOMESCORE < 255)
		{

			//Calculation
			//Calculation:
			//  HOMESCORE = 199
			FCV_HOMESCORE = 199;

		} else {

			//Decision
			//Decision: HOMESCORE = 255?
			if (FCV_HOMESCORE == 255)
			{

				//Calculation
				//Calculation:
				//  HOMESCORE = 0
				FCV_HOMESCORE = 0;

			// } else {

			}

		}

		//Calculation
		//Calculation:
		//  toggle_home = 1
		FCV_TOGGLE_HOME = 1;

	// } else {

	}

	//Decision
	//Decision: btn_guest = 1 AND toggle_guest = 0?
	if (FCV_BTN_GUEST == 1 & FCV_TOGGLE_GUEST == 0)
	{

		//Decision
		//Decision: btn_shift = 1?
		if (FCV_BTN_SHIFT == 1)
		{

			//Calculation
			//Calculation:
			//  GUESTSCORE = GUESTSCORE - 1
			FCV_GUESTSCORE = FCV_GUESTSCORE - 1;

		} else {

			//Calculation
			//Calculation:
			//  GUESTSCORE = GUESTSCORE + 1
			FCV_GUESTSCORE = FCV_GUESTSCORE + 1;

		}

		//Decision
		//Decision: GUESTSCORE >= 200 AND GUESTSCORE < 255?
		if (FCV_GUESTSCORE >= 200 & FCV_GUESTSCORE < 255)
		{

			//Calculation
			//Calculation:
			//  GUESTSCORE = 199
			FCV_GUESTSCORE = 199;

		} else {

			//Decision
			//Decision: GUESTSCORE = 255?
			if (FCV_GUESTSCORE == 255)
			{

				//Calculation
				//Calculation:
				//  GUESTSCORE = 0
				FCV_GUESTSCORE = 0;

			// } else {

			}

		}

		//Calculation
		//Calculation:
		//  toggle_guest = 1
		FCV_TOGGLE_GUEST = 1;

	// } else {

	}

	//Decision
	//Decision: btn_shotclock = 1 AND toggle_shotclock = 0?
	if (FCV_BTN_SHOTCLOCK == 1 & FCV_TOGGLE_SHOTCLOCK == 0)
	{

		//Decision
		//Decision: btn_shift = 1?
		if (FCV_BTN_SHIFT == 1)
		{

			//Calculation
			//Calculation:
			//  SHOTCLOCK = 14
			FCV_SHOTCLOCK = 14;

		} else {

			//Calculation
			//Calculation:
			//  SHOTCLOCK = 24
			FCV_SHOTCLOCK = 24;

		}

		//Calculation
		//Calculation:
		//  toggle_shotclock = 1
		FCV_TOGGLE_SHOTCLOCK = 1;

	// } else {

	}

	//Decision
	//Decision: btn_startstop = 1 AND toggle_startstop = 0?
	if (FCV_BTN_STARTSTOP == 1 & FCV_TOGGLE_STARTSTOP == 0)
	{

		//Decision
		//Decision: btn_shift = 1?
		if (FCV_BTN_SHIFT == 1)
		{

			//Calculation
			//Calculation:
			//  flag_SETTIME = 1
			FCV_FLAG_SETTIME = 1;

		} else {

			//Decision
			//Decision: flag_startstop = 1?
			if (FCV_FLAG_STARTSTOP == 1)
			{

				//Calculation
				//Calculation:
				//  flag_startstop = 0
				FCV_FLAG_STARTSTOP = 0;

			} else {

				//Calculation
				//Calculation:
				//  flag_startstop = 1
				FCV_FLAG_STARTSTOP = 1;

			}

			//Calculation
			//Calculation:
			//  TIME_COUNTER = 0
			FCV_TIME_COUNTER = 0;

		}

		//Calculation
		//Calculation:
		//  toggle_startstop = 1
		FCV_TOGGLE_STARTSTOP = 1;

	// } else {

	}

}


void FCM_TIMEKEEP()
{

	//Decision
	//Decision: flag_startstop = 1?
	if (FCV_FLAG_STARTSTOP == 1)
	{

		//Calculation
		//Calculation:
		//  TIME_COUNTER = TIME_COUNTER + 1
		FCV_TIME_COUNTER = FCV_TIME_COUNTER + 1;

		//Decision
		//Decision: TIME_COUNTER >= 1220?
		if (FCV_TIME_COUNTER >= 1220)
		{

			//Calculation
			//Calculation:
			//  GAMETIME_SEC = GAMETIME_SEC - 1
			//  SHOTCLOCK = SHOTCLOCK - 1
			FCV_GAMETIME_SEC = FCV_GAMETIME_SEC - 1;
			FCV_SHOTCLOCK = FCV_SHOTCLOCK - 1;

			//Decision
			//Decision: GAMETIME_SEC = 255?
			if (FCV_GAMETIME_SEC == 255)
			{

				//Calculation
				//Calculation:
				//  GAMETIME_MIN = GAMETIME_MIN - 1
				//  GAMETIME_SEC = 59
				FCV_GAMETIME_MIN = FCV_GAMETIME_MIN - 1;
				FCV_GAMETIME_SEC = 59;

			// } else {

			}

			//Decision
			//Decision: SHOTCLOCK = 0?
			if (FCV_SHOTCLOCK == 0)
			{

				//Calculation
				//Calculation:
				//  flag_startstop = 0
				FCV_FLAG_STARTSTOP = 0;

			// } else {

			}

			//Calculation
			//Calculation:
			//  TIME_COUNTER = 0
			FCV_TIME_COUNTER = 0;

		// } else {

		}

	// } else {

	}

}


void FCM_DISPLAY_BLINKING()
{

	//Calculation
	//Calculation:
	//  BLINK_count = BLINK_count + 1
	FCV_BLINK_COUNT = FCV_BLINK_COUNT + 1;

	//Comment:
	//GAMETIME

	//Decision
	//Decision: BLINK_COUNT > 20 AND to_SET = 1?
	if (FCV_BLINK_COUNT > 20 & FCV_TO_SET == 1)
	{

		//Decision
		//Decision: BLINK_COUNT > 40?
		if (FCV_BLINK_COUNT > 40)
		{

			//Calculation
			//Calculation:
			//  BLINK_count = 0
			FCV_BLINK_COUNT = 0;

		// } else {

		}

		//Calculation
		//Calculation:
		//  scan1 = 0x00
		//  scan2 = 0x80
		//  TODISPLAY_SS = 255
		FCV_SCAN1 = 0x00;
		FCV_SCAN2 = 0x80;
		FCV_TODISPLAY_SS = 255;

		//Call Macro
		//Call Macro: Display_7Seg()
		FCM_Display_7Seg();

	} else {

		//Calculation
		//Calculation:
		//  scan1 = 0x00
		//  scan2 = 0x80
		//  TODISPLAY_SS = GAMETIME_MIN / 10
		FCV_SCAN1 = 0x00;
		FCV_SCAN2 = 0x80;
		FCV_TODISPLAY_SS = FCV_GAMETIME_MIN / 10;

		//Call Macro
		//Call Macro: Display_7Seg()
		FCM_Display_7Seg();

	}

	//Decision
	//Decision: BLINK_COUNT > 20 AND to_SET = 2?
	if (FCV_BLINK_COUNT > 20 & FCV_TO_SET == 2)
	{

		//Decision
		//Decision: BLINK_COUNT > 40?
		if (FCV_BLINK_COUNT > 40)
		{

			//Calculation
			//Calculation:
			//  BLINK_count = 0
			FCV_BLINK_COUNT = 0;

		// } else {

		}

		//Calculation
		//Calculation:
		//  scan1 = 0x00
		//  scan2 = 0x40
		//  TODISPLAY_SS = 255
		FCV_SCAN1 = 0x00;
		FCV_SCAN2 = 0x40;
		FCV_TODISPLAY_SS = 255;

		//Call Macro
		//Call Macro: Display_7Seg()
		FCM_Display_7Seg();

	} else {

		//Calculation
		//Calculation:
		//  scan1 = 0x00
		//  scan2 = 0x40
		//  TODISPLAY_SS = GAMETIME_MIN MOD 10
		FCV_SCAN1 = 0x00;
		FCV_SCAN2 = 0x40;
		FCV_TODISPLAY_SS = FCV_GAMETIME_MIN % 10;

		//Call Macro
		//Call Macro: Display_7Seg()
		FCM_Display_7Seg();

	}

	//Decision
	//Decision: BLINK_COUNT > 20 AND to_SET = 3?
	if (FCV_BLINK_COUNT > 20 & FCV_TO_SET == 3)
	{

		//Decision
		//Decision: BLINK_COUNT > 40?
		if (FCV_BLINK_COUNT > 40)
		{

			//Calculation
			//Calculation:
			//  BLINK_count = 0
			FCV_BLINK_COUNT = 0;

		// } else {

		}

		//Calculation
		//Calculation:
		//  scan1 = 0x00
		//  scan2 = 0x20
		//  TODISPLAY_SS = 255
		FCV_SCAN1 = 0x00;
		FCV_SCAN2 = 0x20;
		FCV_TODISPLAY_SS = 255;

		//Call Macro
		//Call Macro: Display_7Seg()
		FCM_Display_7Seg();

	} else {

		//Calculation
		//Calculation:
		//  scan1 = 0x00
		//  scan2 = 0x20
		//  TODISPLAY_SS = GAMETIME_SEC / 10
		FCV_SCAN1 = 0x00;
		FCV_SCAN2 = 0x20;
		FCV_TODISPLAY_SS = FCV_GAMETIME_SEC / 10;

		//Call Macro
		//Call Macro: Display_7Seg()
		FCM_Display_7Seg();

	}

	//Decision
	//Decision: BLINK_COUNT > 20 AND to_SET = 4?
	if (FCV_BLINK_COUNT > 20 & FCV_TO_SET == 4)
	{

		//Decision
		//Decision: BLINK_COUNT > 40?
		if (FCV_BLINK_COUNT > 40)
		{

			//Calculation
			//Calculation:
			//  BLINK_count = 0
			FCV_BLINK_COUNT = 0;

		// } else {

		}

		//Calculation
		//Calculation:
		//  scan1 = 0x00
		//  scan2 = 0x10
		//  TODISPLAY_SS = 255
		FCV_SCAN1 = 0x00;
		FCV_SCAN2 = 0x10;
		FCV_TODISPLAY_SS = 255;

		//Call Macro
		//Call Macro: Display_7Seg()
		FCM_Display_7Seg();

	} else {

		//Calculation
		//Calculation:
		//  scan1 = 0x00
		//  scan2 = 0x10
		//  TODISPLAY_SS = GAMETIME_SEC MOD 10
		FCV_SCAN1 = 0x00;
		FCV_SCAN2 = 0x10;
		FCV_TODISPLAY_SS = FCV_GAMETIME_SEC % 10;

		//Call Macro
		//Call Macro: Display_7Seg()
		FCM_Display_7Seg();

	}

	//Decision
	//Decision: BLINK_COUNT > 20 AND to_SET = 5?
	if (FCV_BLINK_COUNT > 20 & FCV_TO_SET == 5)
	{

		//Decision
		//Decision: BLINK_COUNT > 40?
		if (FCV_BLINK_COUNT > 40)
		{

			//Calculation
			//Calculation:
			//  BLINK_count = 0
			FCV_BLINK_COUNT = 0;

		// } else {

		}

		//Calculation
		//Calculation:
		//  scan1 = 0x10
		//  scan2 = 0x00
		//  TODISPLAY_SS = 255
		FCV_SCAN1 = 0x10;
		FCV_SCAN2 = 0x00;
		FCV_TODISPLAY_SS = 255;

		//Call Macro
		//Call Macro: Display_7Seg()
		FCM_Display_7Seg();

	} else {

		//Calculation
		//Calculation:
		//  scan1 = 0x10
		//  scan2 = 0x00
		//  TODISPLAY_SS = SHOTCLOCK / 10
		FCV_SCAN1 = 0x10;
		FCV_SCAN2 = 0x00;
		FCV_TODISPLAY_SS = FCV_SHOTCLOCK / 10;

		//Call Macro
		//Call Macro: Display_7Seg()
		FCM_Display_7Seg();

	}

	//Decision
	//Decision: BLINK_COUNT > 20 AND to_SET = 6?
	if (FCV_BLINK_COUNT > 20 & FCV_TO_SET == 6)
	{

		//Decision
		//Decision: BLINK_COUNT > 40?
		if (FCV_BLINK_COUNT > 40)
		{

			//Calculation
			//Calculation:
			//  BLINK_count = 0
			FCV_BLINK_COUNT = 0;

		// } else {

		}

		//Calculation
		//Calculation:
		//  scan1 = 0x08
		//  scan2 = 0x00
		//  TODISPLAY_SS = 255
		FCV_SCAN1 = 0x08;
		FCV_SCAN2 = 0x00;
		FCV_TODISPLAY_SS = 255;

		//Call Macro
		//Call Macro: Display_7Seg()
		FCM_Display_7Seg();

	} else {

		//Calculation
		//Calculation:
		//  scan1 = 0x08
		//  scan2 = 0x00
		//  TODISPLAY_SS = SHOTCLOCK MOD 10
		FCV_SCAN1 = 0x08;
		FCV_SCAN2 = 0x00;
		FCV_TODISPLAY_SS = FCV_SHOTCLOCK % 10;

		//Call Macro
		//Call Macro: Display_7Seg()
		FCM_Display_7Seg();

	}

	//Decision
	//Decision: BLINK_COUNT > 20 AND to_SET = 7?
	if (FCV_BLINK_COUNT > 20 & FCV_TO_SET == 7)
	{

		//Decision
		//Decision: BLINK_COUNT > 40?
		if (FCV_BLINK_COUNT > 40)
		{

			//Calculation
			//Calculation:
			//  BLINK_count = 0
			FCV_BLINK_COUNT = 0;

		// } else {

		}

		//Calculation
		//Calculation:
		//  scan1 = 0x04
		//  scan2 = 0x00
		//  TODISPLAY_SS = 255
		FCV_SCAN1 = 0x04;
		FCV_SCAN2 = 0x00;
		FCV_TODISPLAY_SS = 255;

		//Call Macro
		//Call Macro: Display_7Seg()
		FCM_Display_7Seg();

	} else {

		//Calculation
		//Calculation:
		//  scan1 = 0x04
		//  scan2 = 0x00
		//  TODISPLAY_SS = PERIOD
		FCV_SCAN1 = 0x04;
		FCV_SCAN2 = 0x00;
		FCV_TODISPLAY_SS = FCV_PERIOD;

		//Call Macro
		//Call Macro: Display_7Seg()
		FCM_Display_7Seg();

	}

	//Comment:
	//HOME SCORE

	//Calculation
	//Calculation:
	//  scan1 = 0x00
	//  scan2 = 0x08
	//  TODISPLAY_SS = HOMESCORE / 100
	FCV_SCAN1 = 0x00;
	FCV_SCAN2 = 0x08;
	FCV_TODISPLAY_SS = FCV_HOMESCORE / 100;

	//Decision
	//Decision: TODISPLAY_SS = 0?
	if (FCV_TODISPLAY_SS == 0)
	{

		//Calculation
		//Calculation:
		//  TODISPLAY_SS = 255
		FCV_TODISPLAY_SS = 255;

	// } else {

	}

	//Call Macro
	//Call Macro: Display_7Seg()
	FCM_Display_7Seg();

	//Calculation
	//Calculation:
	//  scan1 = 0x00
	//  scan2 = 0x04
	//  TODISPLAY_SS = (HOMESCORE MOD 100) / 10
	FCV_SCAN1 = 0x00;
	FCV_SCAN2 = 0x04;
	FCV_TODISPLAY_SS = (FCV_HOMESCORE % 100) / 10;

	//Decision
	//Decision: TODISPLAY_SS = 0 AND HOMESCORE < 100?
	if (FCV_TODISPLAY_SS == 0 & FCV_HOMESCORE < 100)
	{

		//Calculation
		//Calculation:
		//  TODISPLAY_SS = 255
		FCV_TODISPLAY_SS = 255;

	// } else {

	}

	//Call Macro
	//Call Macro: Display_7Seg()
	FCM_Display_7Seg();

	//Calculation
	//Calculation:
	//  scan1 = 0x00
	//  scan2 = 0x02
	//  TODISPLAY_SS = HOMESCORE MOD 10
	FCV_SCAN1 = 0x00;
	FCV_SCAN2 = 0x02;
	FCV_TODISPLAY_SS = FCV_HOMESCORE % 10;

	//Call Macro
	//Call Macro: Display_7Seg()
	FCM_Display_7Seg();

	//Comment:
	//GUEST SCORE

	//Calculation
	//Calculation:
	//  scan1 = 0x00
	//  scan2 = 0x01
	//  TODISPLAY_SS = GUESTSCORE / 100
	FCV_SCAN1 = 0x00;
	FCV_SCAN2 = 0x01;
	FCV_TODISPLAY_SS = FCV_GUESTSCORE / 100;

	//Decision
	//Decision: TODISPLAY_SS = 0?
	if (FCV_TODISPLAY_SS == 0)
	{

		//Calculation
		//Calculation:
		//  TODISPLAY_SS = 255
		FCV_TODISPLAY_SS = 255;

	// } else {

	}

	//Call Macro
	//Call Macro: Display_7Seg()
	FCM_Display_7Seg();

	//Calculation
	//Calculation:
	//  scan1 = 0x80
	//  scan2 = 0x00
	//  TODISPLAY_SS = (GUESTSCORE MOD 100) / 10
	FCV_SCAN1 = 0x80;
	FCV_SCAN2 = 0x00;
	FCV_TODISPLAY_SS = (FCV_GUESTSCORE % 100) / 10;

	//Decision
	//Decision: TODISPLAY_SS = 0 AND GUESTSCORE < 100?
	if (FCV_TODISPLAY_SS == 0 & FCV_GUESTSCORE < 100)
	{

		//Calculation
		//Calculation:
		//  TODISPLAY_SS = 255
		FCV_TODISPLAY_SS = 255;

	// } else {

	}

	//Call Macro
	//Call Macro: Display_7Seg()
	FCM_Display_7Seg();

	//Calculation
	//Calculation:
	//  scan1 = 0x40
	//  scan2 = 0x00
	//  TODISPLAY_SS = GUESTSCORE MOD 10
	FCV_SCAN1 = 0x40;
	FCV_SCAN2 = 0x00;
	FCV_TODISPLAY_SS = FCV_GUESTSCORE % 10;

	//Call Macro
	//Call Macro: Display_7Seg()
	FCM_Display_7Seg();

}


void FCM_button_condition_SETTING()
{

	//Decision
	//Decision: btn_shotclock = 1 AND toggle_shotclock = 0?
	if (FCV_BTN_SHOTCLOCK == 1 & FCV_TOGGLE_SHOTCLOCK == 0)
	{

		//Calculation
		//Calculation:
		//  to_SET = to_SET + 1
		FCV_TO_SET = FCV_TO_SET + 1;

		//Calculation
		//Calculation:
		//  toggle_shotclock = 1
		FCV_TOGGLE_SHOTCLOCK = 1;

		//Decision
		//Decision: to_SET = 8?
		if (FCV_TO_SET == 8)
		{

			//Calculation
			//Calculation:
			//  to_SET = 1
			FCV_TO_SET = 1;

		// } else {

		}

	// } else {

	}

}



void main()
{
	//Initialization
	cmcon = 0x07;


	//Interrupt initialization code
	option_reg = 0xC0;


	//Interrupt
	//Interrupt: Enable TMR2
	st_bit(intcon,PEIE);
	cr_bit(t2con,T2CKPS0);
	st_bit(t2con,T2CKPS1);
	st_bit(t2con,TMR2ON);
	t2con = (t2con & 0x07) | 0x78;
	pr2=16-1;
	st_bit(intcon,GIE);
	st_bit(pie1, TMR2IE);

	//Calculation
	//Calculation:
	//  GAMETIME_MIN = 10
	//  GAMETIME_SEC = 0
	//  SHOTCLOCK = 24
	FCV_GAMETIME_MIN = 10;
	FCV_GAMETIME_SEC = 0;
	FCV_SHOTCLOCK = 24;

	//Calculation
	//Calculation:
	//  HOMESCORE = 0
	//  GUESTSCORE = 0
	//  PERIOD = 1
	//  button_SCAN = 0
	FCV_HOMESCORE = 0;
	FCV_GUESTSCORE = 0;
	FCV_PERIOD = 1;
	FCV_BUTTON_SCAN = 0;

	//Calculation
	//Calculation:
	//  flag_startstop = 1
	FCV_FLAG_STARTSTOP = 1;

	//Loop
	//Loop: Loop 100 times
	for (FCLV_LOOP1=0; FCLV_LOOP1<100; FCLV_LOOP1++)
	{

		//Call Macro
		//Call Macro: DISPLAY_BOARD_DATA()
		FCM_DISPLAY_BOARD_DATA();

		//Call Macro
		//Call Macro: Interrupt()
		FCM_Interrupt();


	}

	//Calculation
	//Calculation:
	//  btn_buzzer = 0
	//  btn_guest = 0
	//  btn_home = 0
	//  btn_shift = 0
	//  btn_shotclock = 0
	//  btn_startstop = 0
	//  flag_startstop = 0
	//  to_SET = 1
	FCV_BTN_BUZZER = 0;
	FCV_BTN_GUEST = 0;
	FCV_BTN_HOME = 0;
	FCV_BTN_SHIFT = 0;
	FCV_BTN_SHOTCLOCK = 0;
	FCV_BTN_STARTSTOP = 0;
	FCV_FLAG_STARTSTOP = 0;
	FCV_TO_SET = 1;

	//Loop
	//Loop: While 1
	while (1)
	{

		//Decision
		//Decision: flag_SETTIME = 1?
		if (FCV_FLAG_SETTIME == 1)
		{

			//Call Macro
			//Call Macro: DISPLAY_BLINKING()
			FCM_DISPLAY_BLINKING();

			//Call Macro
			//Call Macro: Interrupt()
			FCM_Interrupt();

			//Call Macro
			//Call Macro: button_condition_SETTING()
			FCM_button_condition_SETTING();

		} else {

			//Call Macro
			//Call Macro: DISPLAY_BOARD_DATA()
			FCM_DISPLAY_BOARD_DATA();

			//Call Macro
			//Call Macro: Interrupt()
			FCM_Interrupt();

			//Call Macro
			//Call Macro: button_conditions()
			FCM_button_conditions();

		}


	}

	mainendloop: goto mainendloop;
}

void MX_INTERRUPT_MACRO(void)
{
	//Handler code for [TMR2]
	#ifndef MX_INTHANDLER_pir1_TMR2IF
	#define MX_INTHANDLER_pir1_TMR2IF
	if (ts_bit(pir1, TMR2IF) && ts_bit(pie1, TMR2IE))
	{
		#ifdef USE_FLOWCODE_ICD
			extern char ICD_Interrupt_Enable = 1;
		#endif	
		FCM_TIMEKEEP();
		cr_bit(pir1, TMR2IF);
		#ifdef USE_FLOWCODE_ICD
			extern char ICD_Interrupt_Enable = 0;
		#endif	
	}
	#else
	#warning "This interrupt has previously been enabled, so the macro <TIMEKEEP> may never get called."
	#endif


}



